name: testing access

on:
  workflow_dispatch:

jobs:
  check_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the user is approved
        run: |
          approved_users="${{ secrets.APPROVED_USERS }}"
          IFS=',' read -ra users <<< "$approved_users"
          is_approved=false
          for user in "${users[@]}"; do
            if [ "$user" = "$GITHUB_ACTOR" ]; then
              is_approved=true
              break
            fi
          done

          if [ "$is_approved" != "true" ]; then
            echo "Error: You are not an approved user to run this workflow."
            exit 1
          fi

      # Add your regular workflow steps below
      # ...
