name: My Workflow

on:
  workflow_dispatch:
env:
  USER1: ${{ secrets.USER1 }}
  USER2: ${{ secrets.USER2 }}

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Condition
        run: |
          if [[ ("$GITHUB_ACTOR" == "${{ secrets.USER1 }}" || "$GITHUB_ACTOR" == "${{ secrets.USER2 }}") ]]; then
            echo "Condition met: USER1 or USER2"
      # Add your desired actions or commands here for the condition being true
            
      # Add your desired actions or commands here for the condition being false
  

      
