name: My Workflow

on:
  workflow_dispatch:
env:
  USER1: ${{ secrets.USER1 }}
  USER2: ${{ secrets.USER2 }}

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Condition
        run: |
          if [ "$GITHUB_ACTOR" == "${{env.USER1}}" ] || [ "$GITHUB_ACTOR" == "${{env.USER2}}" ]; then
            echo "Condition met: USER1 or USER2"
            will approve to run workflow
          else
            echo "Condition not met"
            un authorised
          fi
