name: VSworkflow

on:
  workflow_dispatch:

jobs:
  check_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the user is authorized
        env:
          AUTHORIZED_USERS: ${{ secrets.AUTHORIZED_USERS }}
        run: |
          if [[ ",${AUTHORIZED_USERS}," != *",$GITHUB_ACTOR,"* ]]; then
            echo "Error: You are not an authorized user to run this workflow."
            exit 1
          fi

      # Add your regular workflow steps below
      # ...
